export const MAX_CHAIN_DEPTH = 20;

export const THREAD_LINK_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FORWARDED: 'FORWARDED',
  CANCELLED: 'CANCELLED',
} as const;

export const TODO_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  BLOCKED: 'BLOCKED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
